CREATE TABLE IF NOT EXISTS saved_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    question TEXT,
    sparql TEXT NOT NULL,
    result_summary TEXT,
    share_token VARCHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_saved_queries_share_token ON saved_queries(share_token);
CREATE INDEX IF NOT EXISTS idx_saved_queries_tenant_id ON saved_queries(tenant_id);
